config/routes.rb
Rails.application.routes.draw do

  # MUST come first (before the `api` namespace):
  # https://github.com/lynndylanhurley/devise_token_auth#can-i-use-this-gem-alongside-standard-devise
  devise_for :users
  # Required for Devise
  root 'welcome#index'
  # Token auth routes available at `/api/auth`
  namespace :api, defaults: { format: :json } do
    mount_devise_token_auth_for 'User', at: 'auth'
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  concern :copyable do
    get 'copy/:copy', action: :new, on: :collection, as: :copy
  end

  # get 'jobs' => 'jobs#index'

  resources :jobs, only:[:index, :show, :destroy] do
    get 'run' => 'jobs#run', as: :run
  end

  post 'recommendations/update_admin_seeds' => 'recommendation_seeds#update_admin_recommendations', as: :update_admin_recommendations

  put 'providers/update_all' => 'providers#update_all', as: :update_all_providers
  get 'providers/names' => 'providers#names', as: :provider_names
  get 'providers' => 'providers#index', as: :providers

  get 'applications' =>'ingredients#applications', as: :applications
  get 'templates' =>'ingredients#templates', as: :templates
  delete 'recommendations/:recommendation_id' => 'deployment_recommendations#destroy', as: :delete_recommendation

  resources :ingredients, concerns: [:paginatable] do
    post 'trigger_range' => 'deployment_recommendations#trigger_range', as: :trigger_range
    get 'recommendations_completed' => 'ingredients#recommendations_completed', as: :recommendations_completed
    get 'recommendations' => 'deployment_recommendations#index', as: :recommendations
    delete 'recommendations' => 'deployment_recommendations#destroy_all', as: :destroy_all_recommendations
    get 'has_recommendations' => 'deployment_recommendations#has_recommendations', as: :has_recommendations
    get 'copy' => 'ingredients#copy', as: :copy_ingredient
    get 'template' => 'ingredients#template', as: :make_template
    get 'instance' => 'ingredients#instance', as: :instance
    get 'instances' =>'ingredients#instances', as: :instances
  end

  resources :constraints, only: [:show, :index, :destroy, :create, :update], concerns: [:paginatable]

  resources :ram_workloads, only: [:show, :index, :destroy, :create, :update, :new], concerns: [:paginatable]

  resources :cpu_workloads, only: [:show, :index, :destroy, :create, :update, :new], concerns: [:paginatable]

  resources :traffic_workloads, only: [:show, :index, :destroy, :create, :update, :new], concerns: [:paginatable]

  resources :scaling_workloads, concerns: [:paginatable]

  get 'resources_region_areas' => 'resources#region_areas', as: :region_areas
  resources :resources, only: [:show, :index], concerns: [:paginatable]


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_footer.html.haml
%footer.cs-footer
  .container
    %ul
      %li= link_to(t('.about'), nil)
      %li= link_to(t('.faq'), nil)
      %li= link_to(t('.help'), nil)
      %li= link_to(t('.pricing'), nil)
    2016, The Cloud Stove.
    - if defined?(Footnotes) && Footnotes.enabled
      = link_to(t('.toggle_debug_info'), '#footnotes_holder',
          data: { toggle: :collapse } )
    - if Rails.env.development?
      \|
      = link_to(t('.toggle_grid'), "javascript:$('body')[0].classList.toggle('with-baseline-grid');")
    
- if defined?(Footnotes) && Footnotes.enabled
  #footnotes_holder.collapse

app/views/shared/_main_navigation.html.haml
%nav.main-nav.navbar-full
  .container
    %button.navbar-toggler.hidden-sm-up{type: 'button', data: { toggle: 'collapse', target: '#exMainNavbar'}}
      = icon('navicon')
      Cloud Stove
    #exMainNavbar.collapse.navbar-toggleable-xs
      = link_to root_path, class: 'pull-left hidden-xs-down', style: 'width: 2.275rem; height: 2.275rem; padding: .3rem 0;' do
        = inline_svg 'flame.svg', width: '100%', height: '100%'
      = link_to root_path, class: 'navbar-brand hidden-xs-down' do
        The Stove
      .nav.navbar-nav
        = nav_link t('.ingredients'), ingredients_path
        = nav_link t('.cloud_applications'), applications_path
        = nav_link t('.templates'), templates_path
        = nav_link t('.providers'), providers_path
        = nav_link t('.jobs'), jobs_path
      .navbar-right
        .nav.navbar-nav
          .btn-group
            %button.btn.btn-link.nav-link.dropdown-toggle{data: { toggle: 'dropdown' }, id: 'user_dropdown_id'}
              -# = icon 'user'
              %span.hidden-sm-down Arthur Dent
              = image_tag "//#{Rails.configuration.x.gravatar_host}/avatar/#{Digest::MD5.hexdigest('inzinger@gmail.com')}", class: 'avatar'
            .dropdown-menu.dropdown-menu-right
              = link_to icon('user', t('.my_account')), root_path, class: 'dropdown-item'
              .dropdown-divider
              - if signed_in?
                = button_to(destroy_user_session_path, { method: :delete, class: 'dropdown-item', id: 'signout_btn_id' } ) { icon('sign-out', t('.logout')) }
              - else
                = button_to(new_user_session_path, { method: :get, class: 'dropdown-item', id: 'signin_btn_id'} ) { icon('sign-in', t('.login')) }