config/routes.rb
Rails.application.routes.draw do

  # MUST come first (before the `api` namespace):
  # https://github.com/lynndylanhurley/devise_token_auth#can-i-use-this-gem-alongside-standard-devise
  devise_for :users
  # Required for Devise
  root 'welcome#index'
  # Token auth routes available at `/api/auth`
  namespace :api, defaults: { format: :json } do
    mount_devise_token_auth_for 'User', at: 'auth'
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  concern :copyable do
    get 'copy/:copy', action: :new, on: :collection, as: :copy
  end

  # get 'jobs' => 'jobs#index'

  resources :jobs, only:[:index, :show, :destroy] do
    get 'run' => 'jobs#run', as: :run
  end

  post 'recommendations/update_admin_seeds' => 'recommendation_seeds#update_admin_recommendations', as: :update_admin_recommendations

  put 'providers/update_all' => 'providers#update_all', as: :update_all_providers
  get 'providers/names' => 'providers#names', as: :provider_names
  get 'providers' => 'providers#index', as: :providers

  get 'applications' =>'ingredients#applications', as: :applications
  get 'templates' =>'ingredients#templates', as: :templates
  delete 'recommendations/:recommendation_id' => 'deployment_recommendations#destroy', as: :delete_recommendation

  resources :ingredients, concerns: [:paginatable] do
    post 'trigger_range' => 'deployment_recommendations#trigger_range', as: :trigger_range
    get 'recommendations_completed' => 'ingredients#recommendations_completed', as: :recommendations_completed
    get 'recommendations' => 'deployment_recommendations#index', as: :recommendations
    delete 'recommendations' => 'deployment_recommendations#destroy_all', as: :destroy_all_recommendations
    get 'has_recommendations' => 'deployment_recommendations#has_recommendations', as: :has_recommendations
    get 'copy' => 'ingredients#copy', as: :copy_ingredient
    get 'template' => 'ingredients#template', as: :make_template
    get 'instance' => 'ingredients#instance', as: :instance
    get 'instances' =>'ingredients#instances', as: :instances
  end

  resources :constraints, only: [:show, :index, :destroy, :create, :update], concerns: [:paginatable]

  resources :ram_workloads, only: [:show, :index, :destroy, :create, :update, :new], concerns: [:paginatable]

  resources :cpu_workloads, only: [:show, :index, :destroy, :create, :update, :new], concerns: [:paginatable]

  resources :traffic_workloads, only: [:show, :index, :destroy, :create, :update, :new], concerns: [:paginatable]

  resources :scaling_workloads, concerns: [:paginatable]

  get 'resources_region_areas' => 'resources#region_areas', as: :region_areas
  resources :resources, only: [:show, :index], concerns: [:paginatable]


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient_from_admin, only: [:show, :instance, :instances]
  before_action :set_ingredient, only: [:edit, :update, :destroy, :copy, :template, :recommendations_completed]
  skip_before_action :authenticate_user!, only: [:templates]
  before_action :authenticate_admin!, only: [:template, :new, :instances]

  # Returns all ingredients (irrespective if template, instance, application) of the current user
  def index
    @ingredients = current_user.ingredients.page(params[:page])
    respond_to do |format|
      format.html
      format.json {render json: @ingredients}
    end
  end

  # Returns applications defined by the current user
  def applications
    @roots = current_user.ingredients.select {|i| i.application_root? && !i.is_template}

    respond_to do |format|
      format.html
      format.json {render json: @roots}
    end
  end

  # Returns all templates, independent of user
  def templates
    @templates = Ingredient.select {|i| i.application_root? && i.is_template}

    respond_to do |format|
      format.html
      format.json {render json: @templates}
    end
  end

  # Returns instances of the template with root ingredient given by params[:ingredient_id]
  def instances
    ensure_ingredient_present; return if performed?
    ensure_application_root; return if performed?
    ensure_template; return if performed?

    @instances = @ingredient.instances
    respond_to do |format|
      format.html
      format.json {render json: @instances}
    end
  end

  # returns the details of the ingredient determined by params[:id]
  def show
    ensure_ingredient_present; return if performed?

    @cpu_constraint = @ingredient.cpu_constraint
    @ram_constraint = @ingredient.ram_constraint
    @region_constraint = @ingredient.preferred_region_area_constraint
    @dependency_constraints = @ingredient.all_dependency_constraints
    @provider_constraint = @ingredient.provider_constraint
    @scaling_constraint = @ingredient.scaling_constraint
    @deployment_recommendation = @ingredient.deployment_recommendations.last.embed_ingredients unless @ingredient.deployment_recommendations.empty?
    respond_to do |format|
      format.html
      format.json {render json: @ingredient}
    end
  end

  # copies an entire hierarchy starting at the root determined by params[:ingredient_id]
  def copy
    ensure_ingredient_present; return if performed?

    copy = @ingredient.copy
    respond_to do |format|
      format.html {redirect_to copy, notice: 'Ingredient hierarchy was successfully copied.'}
      format.json {render json: copy, status: :ok}
    end
  end

  # makes a template out of an hierarchy starting at the root determined by params[:ingredient_id]
  def template
    ensure_ingredient_present; return if performed?
    ensure_application_root; return if performed?
    ensure_no_template; return if performed?

    template = @ingredient.make_template
    respond_to do |format|
      format.html {redirect_to template, notice: 'Template was successfully created.'}
      format.json {render json: template, status: :ok}
    end
  end

  def instance
    ensure_ingredient_present; return if performed?
    ensure_application_root; return if performed?
    ensure_template; return if performed?

    new_instance = @ingredient.instantiate(current_user)
    if new_instance
      respond_to do |format|
        format.html {redirect_to new_instance, notice: 'Template was successfully instantiated.'}
        format.json {render json: new_instance, status: :ok}
      end
    else
      respond_to do |format|
        format.html {redirect_to :back, notice: 'Can only instantiate root template ingredients.'}
        format.json {render json: 'Can only instantiate root template ingredients.', status: :unprocessable_entity}
      end
    end
  end

  def new
   @ingredients = current_user.ingredients
   @ingredient = if params[:copy]
     current_user.ingredients.find(params[:copy]).deep_dup
   else
     Ingredient.new
   end
  end

  def edit
    @ingredients = current_user.ingredients.all # the list of ingredients usable as a parent
  end

  def create
    @ingredients = current_user.ingredients
    @ingredient = Ingredient.new(user: current_user)
    @ingredient.assign_attributes(ingredient_params)
    @ingredient.destroy_all_app_recommendations

    respond_to do |format|
      if @ingredient.save(context: :user_check) # Perform same parent user validation here
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created}
      else
        format.html { render :new }
        format.json { render json: {errors: @ingredient.errors}, status: :internal_server_error }
      end
    end
  end

  def update
    @ingredients = current_user.ingredients
    @ingredient.assign_attributes(ingredient_params)

    respond_to do |format|
      if @ingredient.save(context: :user_check)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render json: @ingredient, status: :ok}
      else
        format.html { render :edit }
        format.json { render json: {errors: @ingredient.errors}, status: :internal_server_error }
      end
    end
  end

  def destroy
    ensure_no_template; return if performed?

    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient and its subtree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recommendations_completed
    are_recommendations_completed = @ingredient.jobs_completed?
    respond_to do |format|
      format.html { render json: are_recommendations_completed }
      format.json { render json: are_recommendations_completed, status: :ok }
    end
  end

  private

    def set_ingredient_from_admin
      id = params[:id] || params[:ingredient_id]
      @ingredient = set_ingredient || User.stove_admin.ingredients.find_by_id(id)
    end

    def set_ingredient
      id = params[:id] || params[:ingredient_id]
      @ingredient = current_user.ingredients.find_by_id(id)
    end

    def ensure_ingredient_present
      if @ingredient.nil?
        respond_to do |format|
          format.html {redirect_to :templates, notice: 'Ingredient not found.'}
          format.json {render json: 'Ingredient not found.', status: :not_found}
        end
      end
    end

    def ensure_application_root
      unless @ingredient.application_root?
        respond_to do |format|
          format.html { redirect_to :back, notice: 'Ingredient must be an application root.' }
          format.json { render json: 'Ingredient must be an application root.', status: :unprocessable_entity }
        end
      end
    end

    def ensure_template
      unless @ingredient.is_template
        respond_to do |format|
          format.html {redirect_to :back, notice: 'Ingredient must be a template.'}
          format.json {render json: 'Ingredient must be a template.', status: :unprocessable_entity}
        end
      end
    end

    def ensure_no_template
      if @ingredient.is_template
        respond_to do |format|
          format.html {redirect_to :back, notice: 'Ingredient must be a non-template.'}
          format.json {render json: 'Ingredient must be a non-template.', status: :unprocessable_entity}
        end
      end
    end

    def ingredient_params
      if @ingredient.application_root?
        params.require(:ingredient).permit(:name,:icon,:body,:parent_id,
                                           cpu_workload_attributes: [:id, :ingredient_id, :cspu_user_capacity, :parallelism, :_destroy],
                                           ram_workload_attributes: [:id, :ingredient_id, :ram_mb_required, :ram_mb_required_user_capacity, :ram_mb_growth_per_user, :_destroy],
                                           constraints_as_source_attributes: [:id, :ingredient_id, :target_id, :_destroy],
                                           ram_constraint_attributes:[:id, :ingredient_id, :min_ram, :_destroy],
                                           cpu_constraint_attributes:[:id, :ingredient_id, :min_cpus, :_destroy],
                                           preferred_region_area_constraint_attributes:[:id, :ingredient_id, :preferred_region_area, :_destroy],
                                           provider_constraint_attributes:[:id, :ingredient_id, :preferred_providers, :_destroy])
      else
        params.require(:ingredient).permit(:name,:icon,:body,:parent_id,
                                           cpu_workload_attributes: [:id, :ingredient_id, :cspu_user_capacity, :parallelism, :_destroy],
                                           ram_workload_attributes: [:id, :ingredient_id, :ram_mb_required, :ram_mb_required_user_capacity, :ram_mb_growth_per_user, :_destroy],
                                           constraints_as_source_attributes: [:id, :ingredient_id, :target_id, :_destroy],
                                           ram_constraint_attributes:[:id, :ingredient_id, :min_ram, :_destroy],
                                           cpu_constraint_attributes:[:id, :ingredient_id, :min_cpus, :_destroy],
                                           preferred_region_area_constraint_attributes:[:id, :ingredient_id, :preferred_region_area, :_destroy])
      end
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_constraints_as_source_fields.html.haml
%fieldset
  %hr
  %h3 Dependency Constraint

  .form-group
    = f.label :target
    = f.select :target_id, (@ingredients - [@ingredient]).map { |i| [ i.name, i.id ] }

  .form-group
    = f.check_box :_destroy
    = f.label :_destroy, t('.remove_dependency_constraint')

  %hr

app/views/ingredients/_cpu_constraint_fields.html.haml
%fieldset
  %hr
  %h3 CPU Constraint

  .form-group
    = f.label 'Minimal number of CPUs/cores'
    = f.number_field :min_cpus

  .form-group
    = f.check_box :_destroy
    = f.label :_destroy, t('.remove_cpu_constraint')

  %hr

app/views/ingredients/_form.html.haml
= form_for @ingredient do |f|
  - if @ingredient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:"
      %ul
        - @ingredient.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label 'Icon (Fontawesome)'
    = f.text_field :icon, class: 'form-control'

  .form-group
    = f.label :parent
    %br
    = f.select :parent_id, (@ingredients - [@ingredient]).map { |i| [i.name, i.id] }, { include_blank: true }

  .form-group
    = f.label :body
    = f.text_area :body, rows: 25, class: 'form-control monospace md'

  .form-group
    = f.fields_for :constraints_as_source do |builder|
      = render 'constraints_as_source_fields', f:builder

  .form-group
    = f.fields_for :cpu_constraint do |builder|
      = render 'cpu_constraint_fields', f:builder

  .form-group
    = f.fields_for :ram_constraint do |builder|
      = render 'ram_constraint_fields', f:builder

  .form-group
    = f.fields_for :preferred_region_area_constraint do |builder|
      = render 'preferred_region_area_constraint_fields', f:builder

  .form-group
    = f.fields_for :provider_constraint do |builder|
      = render 'provider_constraint_fields', f:builder

  .form-group
    = link_to_add_fields t('.add_dependency_constraint'), f, :constraints_as_source, DependencyConstraint

  .form-group
    = link_to_add_fields t('.add_cpu_constraint'), f, :cpu_constraint, CpuConstraint

  .form-group
    = link_to_add_fields t('.add_ram_constraint'), f, :ram_constraint, RamConstraint

  .form-group
    = link_to_add_fields t('.add_region_constraint'), f, :preferred_region_area_constraint, PreferredRegionAreaConstraint

  - if @ingredient.application_root?
    .form-group
      = link_to_add_fields t('.add_provider_constraint'), f, :provider_constraint, ProviderConstraint

  .form-group
    = f.submit t('save'), class: 'btn btn-success'
    = link_to t('cancel'), @ingredient, class: 'btn btn-link'

app/views/ingredients/_ingredient.html.haml
.ingredient
  %h3.name= link_to ingredient.name, ingredient
  .body= markdown(body_excerpt(ingredient))

app/views/ingredients/_preferred_region_area_constraint_fields.html.haml
%fieldset
  %hr
  %h3 Region Area Constraint

  .form-group
    = f.label 'Preferred Region'
    = f.select :preferred_region_area, ['EU','US','ASIA','SA']

  .form-group
    = f.check_box :_destroy
    = f.label :_destroy, t('.remove_region_constraint')

  %hr

app/views/ingredients/_provider_constraint_fields.html.haml
%fieldset
  %hr
  %h3 Provider Constraint

  .form-group
    = f.label 'Preferred Providers'
    = f.text_field :preferred_providers

  .form-group
    = f.check_box :_destroy
    = f.label :_destroy, t('.remove_region_constraint')

  %hr

app/views/ingredients/_ram_constraint_fields.html.haml
%fieldset
  %hr
  %h3 RAM Constraint

  .form-group
    = f.label 'Minimal RAM in megabytes'
    = f.number_field :min_ram

  .form-group
    = f.check_box :_destroy
    = f.label :_destroy, t('.remove_ram_constraint')

  %hr

app/views/ingredients/applications.html.haml
%h1.clearfix
  = t('.title')
  = link_to t('.new'), new_ingredient_path, class: 'btn btn-success pull-right'

= render :partial => 'ingredient',:collection => @roots


= link_to t('.new'), new_ingredient_path, class: 'btn btn-success'

app/views/ingredients/edit.html.haml
%h1 Edit ingredient

= render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1.clearfix
  = t('.title')
  = link_to t('.new'), new_ingredient_path, class: 'btn btn-success pull-right'

= render :partial => 'ingredient',:collection => @ingredients

= paginate @ingredients


= link_to t('.new'), new_ingredient_path, class: 'btn btn-success'

app/views/ingredients/instances.html.haml
%h1.clearfix
  = t('.title') + " of "  
  -#=link_to @instances.first.template.name, @instances.first.template

= render :partial => 'ingredient',:collection => @instances

app/views/ingredients/new.html.haml
%h1 New ingredient

= render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%h1{:style => 'text-align: center'}= @ingredient.name
%br
%br
.actions
  = link_to 'Copy', ingredient_copy_ingredient_path(@ingredient), class: 'btn btn-success'
  = link_to 'Create Template', ingredient_make_template_path(@ingredient), class: 'btn btn-success'
  = link_to 'Instantiate', ingredient_instance_path(@ingredient), class: 'btn btn-success'
  = link_to 'Show Instances', ingredient_instances_path(@ingredient), class: 'btn btn-success' if @ingredient.application_root? || @ingredient.is_template?

- if !@deployment_recommendation.nil?
  .row
    .col-lg-6
      .description
        %h5{:style => 'text-align: center'}= 'Description'
        %hr
        = markdown(@ingredient.body)
    .col-lg-6
      .description
        %h5{:style => 'text-align: center'}= 'Deployment Recommendation'
        %hr
        %ul
          %li= "Total cost: #{@deployment_recommendation[:total_cost]} $"
          %li= "VM cost: #{@deployment_recommendation[:vm_cost]} $"
        %table.table
          %thead
            %tr
              %th Ingredient
              %th Resource
              %th Price
              %th Provider
          %tbody
            - @deployment_recommendation[:recommendation].each do |entry|
              %tr
                %td= link_to entry[:ingredient].name, ingredient_path(entry[:ingredient])
                %td= "#{entry[:resource].name}"
                %td= "#{entry[:resource].price_per_month}"
                %td= "#{entry[:resource].provider.name}"
- else
  .row
    .description
      %h5{:style => 'text-align: center'}= 'Description'
      %hr
      = markdown(@ingredient.body)

%br
  - unless @dependency_constraints.length == 0 && @cpu_constraint.nil? && @ram_constraint.nil?
    .description
      %h5{:style => 'text-align: center'}= 'Constraints'
      %hr
      - unless @dependency_constraints.length == 0
        %br
        %h4= 'Dependency Constraints'
        %table.table
          %thead
            %tr
              %th Source Ingredient
              %th Target Ingredient
              %th
          %tbody
            - @dependency_constraints.each do |constraint|
              %tr
                %td= link_to constraint.source.name, ingredient_path(constraint.source)
                %td= link_to constraint.target.name, ingredient_path(constraint.target)
                %td= link_to 'X', constraint_path(constraint), :method => :delete, :data => {:confirm => 'Are you sure?'}, class: 'btn btn-danger'
      .row
        .col-sm-6
          - unless @cpu_constraint.nil?
            %br
            %h4= 'CPU Constraint'
            ="Minimal number of cores: #{@cpu_constraint.min_cpus}"
            = link_to 'X', constraint_path(@cpu_constraint), :method => :delete, :data => {:confirm => 'Are you sure?'}, class: 'btn btn-danger'
        .col-sm-6
          - unless @ram_constraint.nil?
            %br
            %h4= 'RAM Constraint'
            ="Minimal RAM in MB: #{@ram_constraint.min_ram}"
            = link_to 'X', constraint_path(@ram_constraint), :method => :delete, :data => {:confirm => 'Are you sure?'}, class: 'btn btn-danger'
      .row
        .col-sm-6
          - unless @region_constraint.nil?
            %br
            %h4= 'Region Constraint'
            ="Preferred Region: #{@region_constraint.preferred_region_area}"
            = link_to 'X', constraint_path(@region_constraint), :method => :delete, :data => {:confirm => 'Are you sure?'}, class: 'btn btn-danger'
        .col-sm-6
          - unless @provider_constraint.nil?
            %br
            %h4= 'Provider Constraint'
            ="Preferred Providers: #{@provider_constraint.preferred_providers}"
            = link_to 'X', constraint_path(@provider_constraint), :method => :delete, :data => {:confirm => 'Are you sure?'}, class: 'btn btn-danger'
%br
%br
- unless @ingredient.children.length == 0
  .ingredient
    %h5{:style => 'text-align: center'}='Ingredients'
    = render :partial => 'ingredient',:collection => @ingredient.children

.actions
  = link_to 'Edit', edit_ingredient_path(@ingredient), class: 'btn btn-warning'
  = link_to 'Destroy', @ingredient, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
  = link_to 'Back', ingredients_path, class: 'btn btn-link'
  = link_to 'Application Root', @ingredient.application_root, class: 'btn btn-info' unless @ingredient.parent.nil?

%br
%br
= form_tag ingredient_trigger_range_path(@ingredient, method: :post) do
  = label_tag 'Min:'
  = number_field_tag 'min', 1000
  = label_tag 'Max:'
  = number_field_tag 'max', 5000
  = label_tag 'Step:'
  = number_field_tag 'step', 1000
  = submit_tag 'Trigger Range Recommendation', class: 'btn btn-danger'

app/views/ingredients/templates.html.haml
%h1.clearfix
  = t('.title')

= render :partial => 'ingredient',:collection => @templates